/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HelloRouteImport } from './routes/hello'
import { Route as FluentspeakRouteRouteImport } from './routes/fluentspeak/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FluentspeakIndexRouteImport } from './routes/fluentspeak/index'
import { Route as FluentspeakTermsRouteImport } from './routes/fluentspeak/terms'
import { Route as FluentspeakPrivacyRouteImport } from './routes/fluentspeak/privacy'
import { Route as FluentspeakContactRouteImport } from './routes/fluentspeak/contact'
import { Route as FluentspeakAboutRouteImport } from './routes/fluentspeak/about'

const HelloRoute = HelloRouteImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const FluentspeakRouteRoute = FluentspeakRouteRouteImport.update({
  id: '/fluentspeak',
  path: '/fluentspeak',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FluentspeakIndexRoute = FluentspeakIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FluentspeakRouteRoute,
} as any)
const FluentspeakTermsRoute = FluentspeakTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => FluentspeakRouteRoute,
} as any)
const FluentspeakPrivacyRoute = FluentspeakPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => FluentspeakRouteRoute,
} as any)
const FluentspeakContactRoute = FluentspeakContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => FluentspeakRouteRoute,
} as any)
const FluentspeakAboutRoute = FluentspeakAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => FluentspeakRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fluentspeak': typeof FluentspeakRouteRouteWithChildren
  '/hello': typeof HelloRoute
  '/fluentspeak/about': typeof FluentspeakAboutRoute
  '/fluentspeak/contact': typeof FluentspeakContactRoute
  '/fluentspeak/privacy': typeof FluentspeakPrivacyRoute
  '/fluentspeak/terms': typeof FluentspeakTermsRoute
  '/fluentspeak/': typeof FluentspeakIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hello': typeof HelloRoute
  '/fluentspeak/about': typeof FluentspeakAboutRoute
  '/fluentspeak/contact': typeof FluentspeakContactRoute
  '/fluentspeak/privacy': typeof FluentspeakPrivacyRoute
  '/fluentspeak/terms': typeof FluentspeakTermsRoute
  '/fluentspeak': typeof FluentspeakIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fluentspeak': typeof FluentspeakRouteRouteWithChildren
  '/hello': typeof HelloRoute
  '/fluentspeak/about': typeof FluentspeakAboutRoute
  '/fluentspeak/contact': typeof FluentspeakContactRoute
  '/fluentspeak/privacy': typeof FluentspeakPrivacyRoute
  '/fluentspeak/terms': typeof FluentspeakTermsRoute
  '/fluentspeak/': typeof FluentspeakIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fluentspeak'
    | '/hello'
    | '/fluentspeak/about'
    | '/fluentspeak/contact'
    | '/fluentspeak/privacy'
    | '/fluentspeak/terms'
    | '/fluentspeak/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hello'
    | '/fluentspeak/about'
    | '/fluentspeak/contact'
    | '/fluentspeak/privacy'
    | '/fluentspeak/terms'
    | '/fluentspeak'
  id:
    | '__root__'
    | '/'
    | '/fluentspeak'
    | '/hello'
    | '/fluentspeak/about'
    | '/fluentspeak/contact'
    | '/fluentspeak/privacy'
    | '/fluentspeak/terms'
    | '/fluentspeak/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FluentspeakRouteRoute: typeof FluentspeakRouteRouteWithChildren
  HelloRoute: typeof HelloRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hello': {
      id: '/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluentspeak': {
      id: '/fluentspeak'
      path: '/fluentspeak'
      fullPath: '/fluentspeak'
      preLoaderRoute: typeof FluentspeakRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluentspeak/': {
      id: '/fluentspeak/'
      path: '/'
      fullPath: '/fluentspeak/'
      preLoaderRoute: typeof FluentspeakIndexRouteImport
      parentRoute: typeof FluentspeakRouteRoute
    }
    '/fluentspeak/terms': {
      id: '/fluentspeak/terms'
      path: '/terms'
      fullPath: '/fluentspeak/terms'
      preLoaderRoute: typeof FluentspeakTermsRouteImport
      parentRoute: typeof FluentspeakRouteRoute
    }
    '/fluentspeak/privacy': {
      id: '/fluentspeak/privacy'
      path: '/privacy'
      fullPath: '/fluentspeak/privacy'
      preLoaderRoute: typeof FluentspeakPrivacyRouteImport
      parentRoute: typeof FluentspeakRouteRoute
    }
    '/fluentspeak/contact': {
      id: '/fluentspeak/contact'
      path: '/contact'
      fullPath: '/fluentspeak/contact'
      preLoaderRoute: typeof FluentspeakContactRouteImport
      parentRoute: typeof FluentspeakRouteRoute
    }
    '/fluentspeak/about': {
      id: '/fluentspeak/about'
      path: '/about'
      fullPath: '/fluentspeak/about'
      preLoaderRoute: typeof FluentspeakAboutRouteImport
      parentRoute: typeof FluentspeakRouteRoute
    }
  }
}

interface FluentspeakRouteRouteChildren {
  FluentspeakAboutRoute: typeof FluentspeakAboutRoute
  FluentspeakContactRoute: typeof FluentspeakContactRoute
  FluentspeakPrivacyRoute: typeof FluentspeakPrivacyRoute
  FluentspeakTermsRoute: typeof FluentspeakTermsRoute
  FluentspeakIndexRoute: typeof FluentspeakIndexRoute
}

const FluentspeakRouteRouteChildren: FluentspeakRouteRouteChildren = {
  FluentspeakAboutRoute: FluentspeakAboutRoute,
  FluentspeakContactRoute: FluentspeakContactRoute,
  FluentspeakPrivacyRoute: FluentspeakPrivacyRoute,
  FluentspeakTermsRoute: FluentspeakTermsRoute,
  FluentspeakIndexRoute: FluentspeakIndexRoute,
}

const FluentspeakRouteRouteWithChildren =
  FluentspeakRouteRoute._addFileChildren(FluentspeakRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FluentspeakRouteRoute: FluentspeakRouteRouteWithChildren,
  HelloRoute: HelloRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
